#[x1mil]
#	user = "x1mil"
#	script = "/home/x1mil/tf2server"
#        
#[tf2sandbox]
#	user = "tf2sandbox"
#	script = "/home/tf2sandbox/tf2server"
[ssl]
	cert = ""
	priv = ""
[tf2server]
	user = "diamond"
	script = "/home/diamond/LGSM/tf2server"

